config/routes.rb
Rails.application.routes.draw do

  scope '/:locale', :locale => /de|fr|it|en/, :format => /json|html|csv/ do

    resources :words
    get 'export', to: 'words#export', as: :words_export

    resources :categories

    resources :users

    resources :learn_sessions do
      get :learn
      post :check_answer
    end
  end

  root :to => 'infos#home'
end

app/models/learn_session.rb
require 'set' # is needed for method rand_n

class LearnSession

  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  include Mongoid::Attributes::Dynamic

  has_one :user
  has_and_belongs_to_many :words, class_name: "Word", inverse_of: nil
  field :boxes, type: Array, default: []


=begin
  has_and_belongs_to_many :box0,class_name: "Word", inverse_of: nil
  has_and_belongs_to_many :box1,class_name: "Word", inverse_of: nil
  has_and_belongs_to_many :box2,class_name: "Word", inverse_of: nil
  has_and_belongs_to_many :box3,class_name: "Word", inverse_of: nil
  has_and_belongs_to_many :box4,class_name: "Word", inverse_of: nil
=end

  # this array contains four choices (to answer a question) for each word from words. One of them is the correct the
  # other 3 are wrong

  # the idea behind the boxes is the following:
  # first all words go into the first box
  # if a user answers the question for one word correct, the word goes one box up until it's box4
  # a word remains in the current box, when the answer of the user is wrong. It doesn't go one box down!
  # the learnSession is not completed until all words are in box4

  field :completed, type: Boolean, default: false

  attr_accessor :number_of_words
  attr_accessor :number_of_boxes

end

app/controllers/learn_sessions_controller.rb
class LearnSessionsController < ApplicationController
  before_action :set_learn_session, only: [:show, :edit, :update, :destroy]

  # GET /learn_sessions
  # GET /learn_sessions.json
  def index
    @learn_sessions = LearnSession.all
  end

  # GET /learn_sessions/1
  # GET /learn_sessions/1.json
  def show
    @learn_session = LearnSession.find(params[:id])
  end

  # GET /learn_sessions/new
  def new
    @learn_session = LearnSession.new
  end

  # GET /learn_sessions/1/edit
  def edit
  end

  # POST /learn_sessions
  # POST /learn_sessions.json
  def create
    @learn_session = LearnSession.new
    @number_of_words = params[:learn_session][:number_of_words].to_i
    @number_of_boxes = params[:learn_session][:number_of_boxes].to_i
    # intern we need a box more than the user want, because the last box is the "don't show those words again" box
    @number_of_boxes = @number_of_boxes + 1

    @number_of_boxes.times do |i|
      @learn_session.boxes[i] = Array.new
    end


    @words = Word.where(language: locale)
    @random_Words = generate_random_array(@words, @number_of_words )
    @random_Words.each{|rw| @learn_session.words << rw} # maybe this value can get deleted later, but I keep it for the moment

    # all words have to go into the first box. Check the comments in learnSession model for more information
    @random_Words.each{|rw| @learn_session.boxes[0] << [rw.id, rw.name, rw.description]}


    # shuffle is needed because otherwise you will always get the alphabetical oder
    @learn_session.boxes[0] = @learn_session.boxes[0].shuffle

    #for later, when the usermanagement works
    #@learn_session.user = current_user

    respond_to do |format|
      if @learn_session.save
        format.html { redirect_to learn_session_learn_path(@learn_session.id, asked_word: @learn_session.boxes[0][0]),
                                  notice: t('learnSession_create') }
        format.json { render :show, status: :created, location: @learn_session }
      else
        format.html { render :new }
        format.json { render json: @learn_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learn_sessions/1
  # PATCH/PUT /learn_sessions/1.json
  def update
    respond_to do |format|
      if @learn_session.update(learn_session_params)
        format.html { redirect_to @learn_session, notice: t('learnSession_update') }
        format.json { render :show, status: :ok, location: @learn_session }
      else
        format.html { render :edit }
        format.json { render json: @learn_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learn_sessions/1
  # DELETE /learn_sessions/1.json
  def destroy
    @learn_session.destroy
    respond_to do |format|
      format.html { redirect_to learn_sessions_url, notice: t('learnSession_delete') }
      format.json { head :no_content }
    end
  end

  # GET /learn_sessions/1/learn
  def learn
    @learn_session = LearnSession.find(params[:learn_session_id])

    # filling up the 2-D array choice
    @words = Word.where(language: locale)
    @choices = []
    @choices << params[:asked_word][2]

    random_choice = generate_random_array(@words, 4)
    random_choice[0..2].each do |rc|
        #this if else statement is to make sure the correct answer don't show up twice
      if rc.description.equal?(@choices[0])
        @choices << rc[3].description
      else
        @choices << rc.description
      end
    end

    # shuffle the arry because otherwise the correct answer will always at the first object in a array
    @choices.shuffle!

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @learn_session }
    end
  end

  def check_answer
    @learn_session = LearnSession.find(params[:learn_session_id])
    asked_word = Word.find_by(id: params[:asked_word][0])
    user_answer = Word.find_by(description: params[:user_answer])
    # with this index you know on which position the asked_word is in the box array. This is important for example
    # important if you want to assign the next word in the array to asked_word
    @index_asked_word = 0
    @learn_session.boxes.each do |box|
      box.each do |word|
        @index_asked_word = box.index(word) if word[2] == asked_word.description
      end
    end

    # this is the actual validation part of this method
    if asked_word.description == user_answer.description
      catch :exit_nested_loop do
        @learn_session.boxes.each do |box|
          box.each do |word|
            # its word[2] because word is a array of three values
            if word[2] == asked_word.description
              unless @learn_session.boxes.last.include?(word)
                index = @learn_session.boxes.index(box)
                @learn_session.boxes[index + 1] << [asked_word.id, asked_word.name, asked_word.description]
                box.reject!{|w| w[0] == asked_word.id }
                throw :exit_nested_loop
              end
            end
          end
        end
      end
      flash[:notice] = t('learnSession_learn_mode_answer_correct')

      @learn_session.save

      # this if statement checks, if the learn_session is completet (it's completed when all words are in box4)
      if @learn_session.boxes.last.size == @learn_session.words.size
        # this is temporary, after a learn_session is completed the the application should root the user to a specific
        # site
        flash[:notice] = t('learnSession_learn_gratulation_for_finishing_session')
        return redirect_to root_path
      end
    else    # if the answer is wrong this part fires up
      flash[:notice] = " \" #{asked_word.name}\"" + t('means') + " \"#{asked_word.description}\"" +
          t('and_not') + " \"#{user_answer.description}\""
    end

    # this nested loop takes care of iterating trough the all boxes and assigns a new value to params[:asked_word]
    # there's a catch and throw statement which escapes the loop at the point you have a new value for params[:asked_word]
    catch :exit_index_control do
      @learn_session.boxes.each do |box|
        if box.empty? == false
          # this elsif take care, that the user dosen't get asked the same word two times in a row if
          #  possible (it happens, when there is only one word left in the n-1 box)
          if box.length == 1  && asked_word.id == box[0][0] && @learn_session.boxes.index(box) <
              (@learn_session.boxes.length - 2) # minus 2 because length start counting at 1 and arrays at 0
            params[:asked_word] = @learn_session.boxes[@learn_session.boxes.index(box) + 1][0]
          elsif @index_asked_word >= (box.length - 1)
            params[:asked_word] = box[0]
          else
            params[:asked_word] = box[(@index_asked_word + 1)]
          end
          throw :exit_index_control
        end
      end
    end

    redirect_to learn_session_learn_path(@learn_session.id, asked_word: params[:asked_word])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn_session
      @learn_session = LearnSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def learn_session_params
      params[:learn_session]
      params.require(:learn_session).permit(:user, :completed, :words_ids => [] )
    end

  # take the array arr and picks the no_of_values from it and store it in a new array array_off_random_values
  # this method is needed because the sample method of Array doesn't care about duplicates
  def generate_random_array(arr, no_of_values )
    random_numbers = []
    array_of_random_values = []

    random_numbers = rand_n(no_of_values, arr.length)

    i = 0
    while i < no_of_values do
      array_of_random_values << arr[random_numbers[i]]
      i += 1
    end

    return array_of_random_values
  end

  # this method returns a array of unique numbers depending on how much numbers do you need
  # and how big the biggest value should be.
  def rand_n(n, max)
    randoms = Set.new
    loop do
      randoms << rand(max)
      return randoms.to_a if randoms.size >= n
    end
  end
end

app/helpers/learn_sessions_helper.rb
module LearnSessionsHelper
end

app/views/learn_sessions/_choices.html.haml
.row
  .col-xs-12.col-sm-12.col-md-6.choice-1
    = button_to "#{@choices[0]}", controller: 'learn_sessions', :action => 'check_answer',
          learn_session_id: @learn_session.id, :asked_word => params[:asked_word], :user_answer => @choices[0]
  .col-xs-12.col-sm-12.col-md-6.choice-2
    = button_to "#{@choices[1]}", controller: 'learn_sessions', :action => 'check_answer',
          learn_session_id: @learn_session.id, :asked_word => params[:asked_word], :user_answer => @choices[1]
.row
  .col-xs-12.col-sm-6.col-md-6.choice-3
    = button_to "#{@choices[2]}", controller: 'learn_sessions', :action => 'check_answer',
          learn_session_id: @learn_session.id, :asked_word => params[:asked_word], :user_answer => @choices[2]
  .col-xs-12.col-sm-6.col-md-6.choice-4
    = button_to "#{@choices[3]}", controller: 'learn_sessions', :action => 'check_answer',
          learn_session_id: @learn_session.id, :asked_word => params[:asked_word], :user_answer => @choices[3]

app/views/learn_sessions/_form.html.haml
= form_for @learn_session do |f|
  - if @learn_session.errors.any?
    #error_explanation
      %h2= "#{pluralize(@learn_session.errors.count, "error")} prohibited this learn_session from being saved:"
      %ul
        - @learn_session.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/learn_sessions/edit.html.haml
%h1 Editing learn_session

= render 'form'

= link_to 'Show', @learn_session
\|
= link_to 'Back', learn_sessions_path

app/views/learn_sessions/index.html.haml
%h1 Listing learn_sessions

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @learn_sessions.each do |learn_session|
      %tr
        %td= link_to 'Show', learn_session
        %td= link_to 'Edit', edit_learn_session_path(learn_session)
        %td= link_to 'Destroy', learn_session, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Learn session', new_learn_session_path

app/views/learn_sessions/learn.html.haml
%br
.row
  .col-sx-12.col-sm-12.col-md-12
    // this is needed for the learn_session/_choice partial
    .question-field
      %p#notice
        = notice
      %strong
        = params[:asked_word][1] + ': '
      =t('learnSession_question_text')
= render 'learn_sessions/choices'

app/views/learn_sessions/learn_mode.html.haml
%br
  -if params[:index_value].equal? nil
    - params[:index_value] = 0


%p#notice
  = notice
= render @merged_boxes[params[:index_value].to_i]

app/views/learn_sessions/new.html.haml
%h1
  = t('learnSession_new_heading')

= form_for @learn_session do |f|
  .form-group
    = f.label t('learnSession_new_number_of_words')
    = f.select :number_of_words, options_for_select((5..100).step(5))
    %br
    = f.label t('learnSession_new_number_of_boxes')
    = f.select :number_of_boxes, options_for_select(1..10)
    %br
      = f.button fa_icon("fa-play-circle", text: t('learnSession_start')), class: "btn-block"

app/views/learn_sessions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_learn_session_path(@learn_session)
= link_to 'Back', learn_sessions_path