config/routes.rb
Rails.application.routes.draw do

  scope '/:locale', :locale => /de|fr|it|en/, :format => /json|html|csv/ do

    resources :words
    get 'export', to: 'words#export', as: :words_export

    resources :categories

    resources :users

    resources :learn_sessions do
      get :learn
      post :check_answer
    end
  end

  root :to => 'infos#home'
end

app/models/word.rb
class Word
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic


  belongs_to :syntactical_category, class_name: 'Category', inverse_of: nil, autosave: true
  has_and_belongs_to_many :semantical_categories, class_name: 'Category', inverse_of: nil, autosave: true
  field :name, type: String
  field :description, type: String
  field :language, type: String

  # OPTIMIZE: if the word allready exist, it should ask the user if he wants to edit the existing word.
  validates :name, uniqueness: {message: "t('word_warning_already_exists')"},:allow_blank => true

  def self.to_csv(options = {:col_sep => ";"})
    CSV.generate(options) do |csv|
      all.each do |word|
        values = word.attributes.values
        csv.add_row values
      end
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  require 'will_paginate/array'

  def index
    @words = Word.where(language: locale)
    # natural_sort_by is needed because otherwise you get in trouble with the german umlauts
    @words = @words.natural_sort_by{|word| word.name}.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
   @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    @categories = Category.all
    puts @word

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: t("word_create_success") }
        format.json { render :index, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find params[:id]

    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: t("word_update_success") }
        format.json { render :index, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end

    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    flash[:notice] = t(:delete_confirmation)
    redirect_to words_path
  end

  def word_params
    allow = [:name, :description, :syntactical_category, :language, :semantical_categories_ids => []]
    params.require(:word).permit(allow)
  end

  def export
    @words = Word.where(language: locale)
    time = Time.now
    respond_to do |format|
      format.html { redirect_to root_url }
      format.csv { send_data @words.to_csv, filename: "words-#{time.strftime("%Y/%m/%d/%H/%M/%S")}.csv" }
    end
  end
end

app/helpers/word_helper.rb
module WordHelper
end

app/views/words/_form.html.haml
= form_for @word do |w|
  .controls
    = render 'shared/error_messages'
  .form-group
    = w.label t("word_name")
    = w.text_field :name, class: "form-control"
  .field
    = w.label t("word_description")
    = w.text_area :description, class: "form-control"
  .field
    - categories = Category.where(category_type: 'syntactic').where(language: locale).all.map { |category| [category.name, category.id] }
    = w.label t("word_syntactical_category")
    = w.select :syntactical_category, options_for_select(categories, @word.syntactical_category_id.to_s)
  .field
    = w.label t("word_semantical_category")
    .input-append
      - @word['semantical_categories_ids'] = [''] if !@word['semantical_categories_ids'].is_a? Array
      - @word['semantical_categories_ids'].each do |entry|
        = select_tag 'word[semantical_categories_ids][]', options_for_select(Category.where(category_type: 'semantic').where(language: locale).collect{|c| [c.name, c.id]}, entry), :include_blank => true

  %button.btn.btn-default{type: "button", id: 'add'}
    %span.fa.fa-plus
    %button.btn.btn-default.pull-right{type: 'button', id: 'remove'}
      %span.fa.fa-minus
  %br
  %br
  .field
    = w.label t('language')
    - available_languages = ['de', 'en']
    = w.select :language, available_languages
  %br
  %button.btn.btn-default{type: "submit"}
    %i.fa.fa-floppy-o
      = t('save')
  %a.btn.btn-default.pull-right{href: words_path, role: "button"}
    %i.fa.fa-times
      =t('back')

app/views/words/_word.html.haml
.row
  .col-sx-12.col-sm-12.col-md-12
    // this is needed for the learn_session/_choice partial
    .question-field
      %strong
        = word.name + ': '
      =t('learnSession_question')
      =t('learnSession_question_text')
= render 'learn_sessions/choices'
%br

app/views/words/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %h2
      = t('edit_capitalized')
    = render 'form'

app/views/words/index.html.haml
%h1
  = t('words_overview')
.row
  / this if for later you will cann select, what category you want to see, but need js or that
  .col-lg-12
    - categories_array = Category.where(language: locale).map { |category| category.name}
    = select_tag :name, options_for_select(categories_array), {:onchange => 'this.form.submit()'}

.row
  .col-lg-12
    .center-block
      .digg_pagination
        = will_paginate @words

    / I think this function should be later only visible for admins
    = link_to content_tag(:span, ' ', title: t('export_to_csv'), :class => 'fa fa-download pull-right',:aria => {:hidden => "true"}), words_export_path(format: "csv")
    %br

    -for w in @words
      .panel.panel-default
        .panel-heading
          = w.name
          .pull-right
            .btn.btn-default.btn-xs
              = link_to content_tag(:i, nil, class: 'fa fa-eye', title: t('show')), word_path(w)
            .btn.btn-default.btn-xs
              = link_to content_tag(:i, nil, class: 'fa fa-pencil', title: t('edit')), edit_word_path(w)
            .btn.btn-default.btn-xs
              = link_to content_tag(:i, nil, class: 'fa fa-times', title: t('delete')), w, method: :delete, data: {confirm: t('confirmation_question')}

        .panel-body
          = w.description
    .center-block
      .digg_pagination
        = will_paginate @words

app/views/words/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h2
      = t('word_new')
    %br
    = render 'form'

app/views/words/show.html.haml
.row
  .col-lg-12.col-xs-12.flash-card-top.rounded-top-right.rounded-top-left
    %h1
      = @word.name

      %span.pull-right
        %a{:href => words_path}
          %i.fa.fa-angle-left{:style => 'color: black;', :title => t('back')}
        %a{:href => edit_word_path(@word)}
          %i.fa.fa-pencil-square-o{:style => 'color: black;', :title => t('edit')}

.row
  .col-lg-12.col-xs-12.flash-card-content
    = @word.description
.row.border-between
  .col-lg-6.col-xs-6.flash-card-sub-heading.border-right
    %h4
      = t('word_syntactical_category')
  .col-lg-6.col-xs-6.flash-card-sub-heading
    %h4
      = t('word_semantical_category')
.row
  .col-lg-6.col-xs-6.flash-card-content.border-right.rounded-bottom-left
    = @word.syntactical_category.name
  .col-lg-6.col-xs-6.flash-card-content.rounded-bottom-right
    /this part is IMO ugly, but at the moment i can only save the id of the categories as an string, ObjectIDs would be better => have to look at words/_form.html.haml
    - @word.semantical_categories_ids.each do |category_id|
      - Category.where(id: category_id).each do |c|
        = c.name
        %br
    / idea for replacing the the line of code above but not working at the moment
    /- @word['semantical_categories_ids'].each do |category|
    /  = category['name locale']