config/routes.rb
Rails.application.routes.draw do

  scope '/:locale', :locale => /de|fr|it|en/, :format => /json|html|csv/ do

    resources :words
    get 'export', to: 'words#export', as: :words_export

    resources :categories

    resources :users

    resources :learn_sessions do
      get :learn
      post :check_answer
    end
  end

  root :to => 'infos#home'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'Medlang'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    .navbar.navbar-inverse.navbar-static-to.navbar-fixed-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#{root_url}")
          %i.fa.fa-user-md
          Medlang
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li
              = link_to ' ' + t('about'), root_url, :class => 'fa fa-info'
          %ul.nav.navbar-nav.navbar-right
            %li
              =link_to content_tag(:span, ' ' + t('category_library'), :class => 'fa fa-th-list', :aria => {:hidden => "true"}), categories_path
            %li
              =link_to content_tag(:span, ' ' + t('new_category'), :class => 'fa fa-plus', :aria => {:hidden => "true"}), new_category_path
            %li
              =link_to content_tag(:span, ' ' + t('card_libary'), :class => 'fa fa-file-o', :aria => {:hidden => "true"}), words_path
            %li
              =link_to content_tag(:span, ' ' + t('new_card'), :class => 'fa fa-plus', :aria => {:hidden => "true"}), new_word_path
            %li
              =link_to content_tag(:span, ' ' + t('login'), :class => 'fa fa-sign-in', :aria => {:hidden => "true"}), root_url
            %li.dropdown
              %a.dropdown-toggle.fa.fa-flag{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = current_language
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li= link_to 'Deutsch', params.merge({ locale: :de })
                %li= link_to 'Francais', params.merge({ locale: :fr })
                %li= link_to 'Italiano', params.merge({ locale: :it })
                %li= link_to 'English', params.merge({ locale: :en })

    / Content form different pages start here
    .content
      .container
        = yield

    / Footer content
    .navbar.navbar-default.footer
      .container-fluid
        .row.spacer
          .col-sx-12.col-sm-12.col-md-12
        .row
          .col-sx-12.col-sm-12.col-md-12
            %p.text-center
              = t('company')
              %br
              Effingerstrasse 55
              %br
              3008
              = t('city')
              = t('country')
              %br
              %a{href: "http://eonum.ch"} www.eonum.ch
              %br
              =t('email')
              #{mail_to 'info@eonum.ch'}
              %br